# Python stubs generated by omniidl from alquimia.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "AlquimiaApp"
#
__name__ = "AlquimiaApp"
_0_AlquimiaApp = omniORB.openModule("AlquimiaApp", r"alquimia.idl")
_0_AlquimiaApp__POA = omniORB.openModule("AlquimiaApp__POA", r"alquimia.idl")


# struct Hechizo
_0_AlquimiaApp.Hechizo = omniORB.newEmptyClass()
class Hechizo (omniORB.StructBase):
    _NP_RepositoryId = "IDL:AlquimiaApp/Hechizo:1.0"

    def __init__(self, id, nombre, tipo_magia, nivel_poder, efecto, activo):
        self.id = id
        self.nombre = nombre
        self.tipo_magia = tipo_magia
        self.nivel_poder = nivel_poder
        self.efecto = efecto
        self.activo = activo

_0_AlquimiaApp.Hechizo = Hechizo
_0_AlquimiaApp._d_Hechizo  = (omniORB.tcInternal.tv_struct, Hechizo, Hechizo._NP_RepositoryId, "Hechizo", "id", omniORB.tcInternal.tv_long, "nombre", (omniORB.tcInternal.tv_string,0), "tipo_magia", (omniORB.tcInternal.tv_string,0), "nivel_poder", omniORB.tcInternal.tv_long, "efecto", (omniORB.tcInternal.tv_string,0), "activo", omniORB.tcInternal.tv_boolean)
_0_AlquimiaApp._tc_Hechizo = omniORB.tcInternal.createTypeCode(_0_AlquimiaApp._d_Hechizo)
omniORB.registerType(Hechizo._NP_RepositoryId, _0_AlquimiaApp._d_Hechizo, _0_AlquimiaApp._tc_Hechizo)
del Hechizo

# struct Ingrediente
_0_AlquimiaApp.Ingrediente = omniORB.newEmptyClass()
class Ingrediente (omniORB.StructBase):
    _NP_RepositoryId = "IDL:AlquimiaApp/Ingrediente:1.0"

    def __init__(self, id, nombre, origen, potencia_magica, cantidad_disponible, esta_prohibido):
        self.id = id
        self.nombre = nombre
        self.origen = origen
        self.potencia_magica = potencia_magica
        self.cantidad_disponible = cantidad_disponible
        self.esta_prohibido = esta_prohibido

_0_AlquimiaApp.Ingrediente = Ingrediente
_0_AlquimiaApp._d_Ingrediente  = (omniORB.tcInternal.tv_struct, Ingrediente, Ingrediente._NP_RepositoryId, "Ingrediente", "id", omniORB.tcInternal.tv_long, "nombre", (omniORB.tcInternal.tv_string,0), "origen", (omniORB.tcInternal.tv_string,0), "potencia_magica", omniORB.tcInternal.tv_double, "cantidad_disponible", omniORB.tcInternal.tv_long, "esta_prohibido", omniORB.tcInternal.tv_boolean)
_0_AlquimiaApp._tc_Ingrediente = omniORB.tcInternal.createTypeCode(_0_AlquimiaApp._d_Ingrediente)
omniORB.registerType(Ingrediente._NP_RepositoryId, _0_AlquimiaApp._d_Ingrediente, _0_AlquimiaApp._tc_Ingrediente)
del Ingrediente

# struct RecetaAlquimica
_0_AlquimiaApp.RecetaAlquimica = omniORB.newEmptyClass()
class RecetaAlquimica (omniORB.StructBase):
    _NP_RepositoryId = "IDL:AlquimiaApp/RecetaAlquimica:1.0"

    def __init__(self, id, hechizo_id, ingrediente_id, cantidad_requerida, funcion_en_hechizo):
        self.id = id
        self.hechizo_id = hechizo_id
        self.ingrediente_id = ingrediente_id
        self.cantidad_requerida = cantidad_requerida
        self.funcion_en_hechizo = funcion_en_hechizo

_0_AlquimiaApp.RecetaAlquimica = RecetaAlquimica
_0_AlquimiaApp._d_RecetaAlquimica  = (omniORB.tcInternal.tv_struct, RecetaAlquimica, RecetaAlquimica._NP_RepositoryId, "RecetaAlquimica", "id", omniORB.tcInternal.tv_long, "hechizo_id", omniORB.tcInternal.tv_long, "ingrediente_id", omniORB.tcInternal.tv_long, "cantidad_requerida", omniORB.tcInternal.tv_long, "funcion_en_hechizo", (omniORB.tcInternal.tv_string,0))
_0_AlquimiaApp._tc_RecetaAlquimica = omniORB.tcInternal.createTypeCode(_0_AlquimiaApp._d_RecetaAlquimica)
omniORB.registerType(RecetaAlquimica._NP_RepositoryId, _0_AlquimiaApp._d_RecetaAlquimica, _0_AlquimiaApp._tc_RecetaAlquimica)
del RecetaAlquimica

# struct HechizoConIngredientes
_0_AlquimiaApp.HechizoConIngredientes = omniORB.newEmptyClass()
class HechizoConIngredientes (omniORB.StructBase):
    _NP_RepositoryId = "IDL:AlquimiaApp/HechizoConIngredientes:1.0"

    def __init__(self, datos_hechizo, ingredientes, cantidades_requeridas):
        self.datos_hechizo = datos_hechizo
        self.ingredientes = ingredientes
        self.cantidades_requeridas = cantidades_requeridas

_0_AlquimiaApp.HechizoConIngredientes = HechizoConIngredientes
_0_AlquimiaApp._d_HechizoConIngredientes  = (omniORB.tcInternal.tv_struct, HechizoConIngredientes, HechizoConIngredientes._NP_RepositoryId, "HechizoConIngredientes", "datos_hechizo", omniORB.typeMapping["IDL:AlquimiaApp/Hechizo:1.0"], "ingredientes", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:AlquimiaApp/Ingrediente:1.0"], 0), "cantidades_requeridas", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_long, 0))
_0_AlquimiaApp._tc_HechizoConIngredientes = omniORB.tcInternal.createTypeCode(_0_AlquimiaApp._d_HechizoConIngredientes)
omniORB.registerType(HechizoConIngredientes._NP_RepositoryId, _0_AlquimiaApp._d_HechizoConIngredientes, _0_AlquimiaApp._tc_HechizoConIngredientes)
del HechizoConIngredientes

# struct IngredienteConHechizos
_0_AlquimiaApp.IngredienteConHechizos = omniORB.newEmptyClass()
class IngredienteConHechizos (omniORB.StructBase):
    _NP_RepositoryId = "IDL:AlquimiaApp/IngredienteConHechizos:1.0"

    def __init__(self, datos_ingrediente, hechizos, cantidades_usadas):
        self.datos_ingrediente = datos_ingrediente
        self.hechizos = hechizos
        self.cantidades_usadas = cantidades_usadas

_0_AlquimiaApp.IngredienteConHechizos = IngredienteConHechizos
_0_AlquimiaApp._d_IngredienteConHechizos  = (omniORB.tcInternal.tv_struct, IngredienteConHechizos, IngredienteConHechizos._NP_RepositoryId, "IngredienteConHechizos", "datos_ingrediente", omniORB.typeMapping["IDL:AlquimiaApp/Ingrediente:1.0"], "hechizos", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:AlquimiaApp/Hechizo:1.0"], 0), "cantidades_usadas", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_long, 0))
_0_AlquimiaApp._tc_IngredienteConHechizos = omniORB.tcInternal.createTypeCode(_0_AlquimiaApp._d_IngredienteConHechizos)
omniORB.registerType(IngredienteConHechizos._NP_RepositoryId, _0_AlquimiaApp._d_IngredienteConHechizos, _0_AlquimiaApp._tc_IngredienteConHechizos)
del IngredienteConHechizos

# typedef ... HechizoSeq
class HechizoSeq:
    _NP_RepositoryId = "IDL:AlquimiaApp/HechizoSeq:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_AlquimiaApp.HechizoSeq = HechizoSeq
_0_AlquimiaApp._d_HechizoSeq  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:AlquimiaApp/Hechizo:1.0"], 0)
_0_AlquimiaApp._ad_HechizoSeq = (omniORB.tcInternal.tv_alias, HechizoSeq._NP_RepositoryId, "HechizoSeq", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:AlquimiaApp/Hechizo:1.0"], 0))
_0_AlquimiaApp._tc_HechizoSeq = omniORB.tcInternal.createTypeCode(_0_AlquimiaApp._ad_HechizoSeq)
omniORB.registerType(HechizoSeq._NP_RepositoryId, _0_AlquimiaApp._ad_HechizoSeq, _0_AlquimiaApp._tc_HechizoSeq)
del HechizoSeq

# typedef ... IngredienteSeq
class IngredienteSeq:
    _NP_RepositoryId = "IDL:AlquimiaApp/IngredienteSeq:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_AlquimiaApp.IngredienteSeq = IngredienteSeq
_0_AlquimiaApp._d_IngredienteSeq  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:AlquimiaApp/Ingrediente:1.0"], 0)
_0_AlquimiaApp._ad_IngredienteSeq = (omniORB.tcInternal.tv_alias, IngredienteSeq._NP_RepositoryId, "IngredienteSeq", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:AlquimiaApp/Ingrediente:1.0"], 0))
_0_AlquimiaApp._tc_IngredienteSeq = omniORB.tcInternal.createTypeCode(_0_AlquimiaApp._ad_IngredienteSeq)
omniORB.registerType(IngredienteSeq._NP_RepositoryId, _0_AlquimiaApp._ad_IngredienteSeq, _0_AlquimiaApp._tc_IngredienteSeq)
del IngredienteSeq

# typedef ... RecetaSeq
class RecetaSeq:
    _NP_RepositoryId = "IDL:AlquimiaApp/RecetaSeq:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_AlquimiaApp.RecetaSeq = RecetaSeq
_0_AlquimiaApp._d_RecetaSeq  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:AlquimiaApp/RecetaAlquimica:1.0"], 0)
_0_AlquimiaApp._ad_RecetaSeq = (omniORB.tcInternal.tv_alias, RecetaSeq._NP_RepositoryId, "RecetaSeq", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:AlquimiaApp/RecetaAlquimica:1.0"], 0))
_0_AlquimiaApp._tc_RecetaSeq = omniORB.tcInternal.createTypeCode(_0_AlquimiaApp._ad_RecetaSeq)
omniORB.registerType(RecetaSeq._NP_RepositoryId, _0_AlquimiaApp._ad_RecetaSeq, _0_AlquimiaApp._tc_RecetaSeq)
del RecetaSeq

# exception NotFound
_0_AlquimiaApp.NotFound = omniORB.newEmptyClass()
class NotFound (CORBA.UserException):
    _NP_RepositoryId = "IDL:AlquimiaApp/NotFound:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_AlquimiaApp.NotFound = NotFound
_0_AlquimiaApp._d_NotFound  = (omniORB.tcInternal.tv_except, NotFound, NotFound._NP_RepositoryId, "NotFound", "message", (omniORB.tcInternal.tv_string,0))
_0_AlquimiaApp._tc_NotFound = omniORB.tcInternal.createTypeCode(_0_AlquimiaApp._d_NotFound)
omniORB.registerType(NotFound._NP_RepositoryId, _0_AlquimiaApp._d_NotFound, _0_AlquimiaApp._tc_NotFound)
del NotFound

# exception InvalidOperation
_0_AlquimiaApp.InvalidOperation = omniORB.newEmptyClass()
class InvalidOperation (CORBA.UserException):
    _NP_RepositoryId = "IDL:AlquimiaApp/InvalidOperation:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_AlquimiaApp.InvalidOperation = InvalidOperation
_0_AlquimiaApp._d_InvalidOperation  = (omniORB.tcInternal.tv_except, InvalidOperation, InvalidOperation._NP_RepositoryId, "InvalidOperation", "message", (omniORB.tcInternal.tv_string,0))
_0_AlquimiaApp._tc_InvalidOperation = omniORB.tcInternal.createTypeCode(_0_AlquimiaApp._d_InvalidOperation)
omniORB.registerType(InvalidOperation._NP_RepositoryId, _0_AlquimiaApp._d_InvalidOperation, _0_AlquimiaApp._tc_InvalidOperation)
del InvalidOperation

# interface HechizoService
_0_AlquimiaApp._d_HechizoService = (omniORB.tcInternal.tv_objref, "IDL:AlquimiaApp/HechizoService:1.0", "HechizoService")
omniORB.typeMapping["IDL:AlquimiaApp/HechizoService:1.0"] = _0_AlquimiaApp._d_HechizoService
_0_AlquimiaApp.HechizoService = omniORB.newEmptyClass()
class HechizoService :
    _NP_RepositoryId = _0_AlquimiaApp._d_HechizoService[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_AlquimiaApp.HechizoService = HechizoService
_0_AlquimiaApp._tc_HechizoService = omniORB.tcInternal.createTypeCode(_0_AlquimiaApp._d_HechizoService)
omniORB.registerType(HechizoService._NP_RepositoryId, _0_AlquimiaApp._d_HechizoService, _0_AlquimiaApp._tc_HechizoService)

# HechizoService operations and attributes
HechizoService._d_crear = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_boolean), (omniORB.tcInternal.tv_long, ), None)
HechizoService._d_obtener = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:AlquimiaApp/Hechizo:1.0"], ), {_0_AlquimiaApp.NotFound._NP_RepositoryId: _0_AlquimiaApp._d_NotFound})
HechizoService._d_listar = ((), (omniORB.typeMapping["IDL:AlquimiaApp/HechizoSeq:1.0"], ), None)
HechizoService._d_actualizar = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_boolean), (), {_0_AlquimiaApp.NotFound._NP_RepositoryId: _0_AlquimiaApp._d_NotFound})
HechizoService._d_eliminar = ((omniORB.tcInternal.tv_long, ), (), {_0_AlquimiaApp.NotFound._NP_RepositoryId: _0_AlquimiaApp._d_NotFound})
HechizoService._d_obtenerConIngredientes = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:AlquimiaApp/HechizoConIngredientes:1.0"], ), {_0_AlquimiaApp.NotFound._NP_RepositoryId: _0_AlquimiaApp._d_NotFound})

# HechizoService object reference
class _objref_HechizoService (CORBA.Object):
    _NP_RepositoryId = HechizoService._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def crear(self, *args):
        return self._obj.invoke("crear", _0_AlquimiaApp.HechizoService._d_crear, args)

    def obtener(self, *args):
        return self._obj.invoke("obtener", _0_AlquimiaApp.HechizoService._d_obtener, args)

    def listar(self, *args):
        return self._obj.invoke("listar", _0_AlquimiaApp.HechizoService._d_listar, args)

    def actualizar(self, *args):
        return self._obj.invoke("actualizar", _0_AlquimiaApp.HechizoService._d_actualizar, args)

    def eliminar(self, *args):
        return self._obj.invoke("eliminar", _0_AlquimiaApp.HechizoService._d_eliminar, args)

    def obtenerConIngredientes(self, *args):
        return self._obj.invoke("obtenerConIngredientes", _0_AlquimiaApp.HechizoService._d_obtenerConIngredientes, args)

omniORB.registerObjref(HechizoService._NP_RepositoryId, _objref_HechizoService)
_0_AlquimiaApp._objref_HechizoService = _objref_HechizoService
del HechizoService, _objref_HechizoService

# HechizoService skeleton
__name__ = "AlquimiaApp__POA"
class HechizoService (PortableServer.Servant):
    _NP_RepositoryId = _0_AlquimiaApp.HechizoService._NP_RepositoryId


    _omni_op_d = {"crear": _0_AlquimiaApp.HechizoService._d_crear, "obtener": _0_AlquimiaApp.HechizoService._d_obtener, "listar": _0_AlquimiaApp.HechizoService._d_listar, "actualizar": _0_AlquimiaApp.HechizoService._d_actualizar, "eliminar": _0_AlquimiaApp.HechizoService._d_eliminar, "obtenerConIngredientes": _0_AlquimiaApp.HechizoService._d_obtenerConIngredientes}

HechizoService._omni_skeleton = HechizoService
_0_AlquimiaApp__POA.HechizoService = HechizoService
omniORB.registerSkeleton(HechizoService._NP_RepositoryId, HechizoService)
del HechizoService
__name__ = "AlquimiaApp"

# interface IngredienteService
_0_AlquimiaApp._d_IngredienteService = (omniORB.tcInternal.tv_objref, "IDL:AlquimiaApp/IngredienteService:1.0", "IngredienteService")
omniORB.typeMapping["IDL:AlquimiaApp/IngredienteService:1.0"] = _0_AlquimiaApp._d_IngredienteService
_0_AlquimiaApp.IngredienteService = omniORB.newEmptyClass()
class IngredienteService :
    _NP_RepositoryId = _0_AlquimiaApp._d_IngredienteService[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_AlquimiaApp.IngredienteService = IngredienteService
_0_AlquimiaApp._tc_IngredienteService = omniORB.tcInternal.createTypeCode(_0_AlquimiaApp._d_IngredienteService)
omniORB.registerType(IngredienteService._NP_RepositoryId, _0_AlquimiaApp._d_IngredienteService, _0_AlquimiaApp._tc_IngredienteService)

# IngredienteService operations and attributes
IngredienteService._d_crear = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_double, omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_boolean), (omniORB.tcInternal.tv_long, ), None)
IngredienteService._d_obtener = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:AlquimiaApp/Ingrediente:1.0"], ), {_0_AlquimiaApp.NotFound._NP_RepositoryId: _0_AlquimiaApp._d_NotFound})
IngredienteService._d_listar = ((), (omniORB.typeMapping["IDL:AlquimiaApp/IngredienteSeq:1.0"], ), None)
IngredienteService._d_actualizar = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0), omniORB.tcInternal.tv_double, omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_boolean), (), {_0_AlquimiaApp.NotFound._NP_RepositoryId: _0_AlquimiaApp._d_NotFound})
IngredienteService._d_eliminar = ((omniORB.tcInternal.tv_long, ), (), {_0_AlquimiaApp.NotFound._NP_RepositoryId: _0_AlquimiaApp._d_NotFound})
IngredienteService._d_obtenerConHechizos = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:AlquimiaApp/IngredienteConHechizos:1.0"], ), {_0_AlquimiaApp.NotFound._NP_RepositoryId: _0_AlquimiaApp._d_NotFound})

# IngredienteService object reference
class _objref_IngredienteService (CORBA.Object):
    _NP_RepositoryId = IngredienteService._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def crear(self, *args):
        return self._obj.invoke("crear", _0_AlquimiaApp.IngredienteService._d_crear, args)

    def obtener(self, *args):
        return self._obj.invoke("obtener", _0_AlquimiaApp.IngredienteService._d_obtener, args)

    def listar(self, *args):
        return self._obj.invoke("listar", _0_AlquimiaApp.IngredienteService._d_listar, args)

    def actualizar(self, *args):
        return self._obj.invoke("actualizar", _0_AlquimiaApp.IngredienteService._d_actualizar, args)

    def eliminar(self, *args):
        return self._obj.invoke("eliminar", _0_AlquimiaApp.IngredienteService._d_eliminar, args)

    def obtenerConHechizos(self, *args):
        return self._obj.invoke("obtenerConHechizos", _0_AlquimiaApp.IngredienteService._d_obtenerConHechizos, args)

omniORB.registerObjref(IngredienteService._NP_RepositoryId, _objref_IngredienteService)
_0_AlquimiaApp._objref_IngredienteService = _objref_IngredienteService
del IngredienteService, _objref_IngredienteService

# IngredienteService skeleton
__name__ = "AlquimiaApp__POA"
class IngredienteService (PortableServer.Servant):
    _NP_RepositoryId = _0_AlquimiaApp.IngredienteService._NP_RepositoryId


    _omni_op_d = {"crear": _0_AlquimiaApp.IngredienteService._d_crear, "obtener": _0_AlquimiaApp.IngredienteService._d_obtener, "listar": _0_AlquimiaApp.IngredienteService._d_listar, "actualizar": _0_AlquimiaApp.IngredienteService._d_actualizar, "eliminar": _0_AlquimiaApp.IngredienteService._d_eliminar, "obtenerConHechizos": _0_AlquimiaApp.IngredienteService._d_obtenerConHechizos}

IngredienteService._omni_skeleton = IngredienteService
_0_AlquimiaApp__POA.IngredienteService = IngredienteService
omniORB.registerSkeleton(IngredienteService._NP_RepositoryId, IngredienteService)
del IngredienteService
__name__ = "AlquimiaApp"

# interface RecetaAlquimicaService
_0_AlquimiaApp._d_RecetaAlquimicaService = (omniORB.tcInternal.tv_objref, "IDL:AlquimiaApp/RecetaAlquimicaService:1.0", "RecetaAlquimicaService")
omniORB.typeMapping["IDL:AlquimiaApp/RecetaAlquimicaService:1.0"] = _0_AlquimiaApp._d_RecetaAlquimicaService
_0_AlquimiaApp.RecetaAlquimicaService = omniORB.newEmptyClass()
class RecetaAlquimicaService :
    _NP_RepositoryId = _0_AlquimiaApp._d_RecetaAlquimicaService[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_AlquimiaApp.RecetaAlquimicaService = RecetaAlquimicaService
_0_AlquimiaApp._tc_RecetaAlquimicaService = omniORB.tcInternal.createTypeCode(_0_AlquimiaApp._d_RecetaAlquimicaService)
omniORB.registerType(RecetaAlquimicaService._NP_RepositoryId, _0_AlquimiaApp._d_RecetaAlquimicaService, _0_AlquimiaApp._tc_RecetaAlquimicaService)

# RecetaAlquimicaService operations and attributes
RecetaAlquimicaService._d_crear = ((omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (omniORB.tcInternal.tv_long, ), {_0_AlquimiaApp.InvalidOperation._NP_RepositoryId: _0_AlquimiaApp._d_InvalidOperation})
RecetaAlquimicaService._d_obtener = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:AlquimiaApp/RecetaAlquimica:1.0"], ), {_0_AlquimiaApp.NotFound._NP_RepositoryId: _0_AlquimiaApp._d_NotFound})
RecetaAlquimicaService._d_listar = ((), (omniORB.typeMapping["IDL:AlquimiaApp/RecetaSeq:1.0"], ), None)
RecetaAlquimicaService._d_actualizar = ((omniORB.tcInternal.tv_long, omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (), {_0_AlquimiaApp.NotFound._NP_RepositoryId: _0_AlquimiaApp._d_NotFound})
RecetaAlquimicaService._d_eliminar = ((omniORB.tcInternal.tv_long, ), (), {_0_AlquimiaApp.NotFound._NP_RepositoryId: _0_AlquimiaApp._d_NotFound})
RecetaAlquimicaService._d_obtenerPorHechizo = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:AlquimiaApp/RecetaSeq:1.0"], ), None)
RecetaAlquimicaService._d_obtenerPorIngrediente = ((omniORB.tcInternal.tv_long, ), (omniORB.typeMapping["IDL:AlquimiaApp/RecetaSeq:1.0"], ), None)

# RecetaAlquimicaService object reference
class _objref_RecetaAlquimicaService (CORBA.Object):
    _NP_RepositoryId = RecetaAlquimicaService._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def crear(self, *args):
        return self._obj.invoke("crear", _0_AlquimiaApp.RecetaAlquimicaService._d_crear, args)

    def obtener(self, *args):
        return self._obj.invoke("obtener", _0_AlquimiaApp.RecetaAlquimicaService._d_obtener, args)

    def listar(self, *args):
        return self._obj.invoke("listar", _0_AlquimiaApp.RecetaAlquimicaService._d_listar, args)

    def actualizar(self, *args):
        return self._obj.invoke("actualizar", _0_AlquimiaApp.RecetaAlquimicaService._d_actualizar, args)

    def eliminar(self, *args):
        return self._obj.invoke("eliminar", _0_AlquimiaApp.RecetaAlquimicaService._d_eliminar, args)

    def obtenerPorHechizo(self, *args):
        return self._obj.invoke("obtenerPorHechizo", _0_AlquimiaApp.RecetaAlquimicaService._d_obtenerPorHechizo, args)

    def obtenerPorIngrediente(self, *args):
        return self._obj.invoke("obtenerPorIngrediente", _0_AlquimiaApp.RecetaAlquimicaService._d_obtenerPorIngrediente, args)

omniORB.registerObjref(RecetaAlquimicaService._NP_RepositoryId, _objref_RecetaAlquimicaService)
_0_AlquimiaApp._objref_RecetaAlquimicaService = _objref_RecetaAlquimicaService
del RecetaAlquimicaService, _objref_RecetaAlquimicaService

# RecetaAlquimicaService skeleton
__name__ = "AlquimiaApp__POA"
class RecetaAlquimicaService (PortableServer.Servant):
    _NP_RepositoryId = _0_AlquimiaApp.RecetaAlquimicaService._NP_RepositoryId


    _omni_op_d = {"crear": _0_AlquimiaApp.RecetaAlquimicaService._d_crear, "obtener": _0_AlquimiaApp.RecetaAlquimicaService._d_obtener, "listar": _0_AlquimiaApp.RecetaAlquimicaService._d_listar, "actualizar": _0_AlquimiaApp.RecetaAlquimicaService._d_actualizar, "eliminar": _0_AlquimiaApp.RecetaAlquimicaService._d_eliminar, "obtenerPorHechizo": _0_AlquimiaApp.RecetaAlquimicaService._d_obtenerPorHechizo, "obtenerPorIngrediente": _0_AlquimiaApp.RecetaAlquimicaService._d_obtenerPorIngrediente}

RecetaAlquimicaService._omni_skeleton = RecetaAlquimicaService
_0_AlquimiaApp__POA.RecetaAlquimicaService = RecetaAlquimicaService
omniORB.registerSkeleton(RecetaAlquimicaService._NP_RepositoryId, RecetaAlquimicaService)
del RecetaAlquimicaService
__name__ = "AlquimiaApp"

#
# End of module "AlquimiaApp"
#
__name__ = "alquimia_idl"

_exported_modules = ( "AlquimiaApp", )

# The end.
