# DO NOT EDIT THIS FILE!
#
# Python module AlquimiaApp__POA generated by omniidl

import omniORB
omniORB.updateModule("AlquimiaApp__POA")

# ** 1. Stub files contributing to this module
import alquimia_idl

# ** 2. Sub-modules

# ** 3. End
