# DO NOT EDIT THIS FILE!
#
# Python module AlquimiaApp generated by omniidl

import omniORB
omniORB.updateModule("AlquimiaApp")

# ** 1. Stub files contributing to this module
import alquimia_idl

# ** 2. Sub-modules

# ** 3. End
